[package]
name = "tlrc"
version = "1.1.0"
description = "A tldr client written in Rust"
categories = ["command-line-utilities"]
homepage = "https://github.com/acuteenvy/tlrc"
repository = "https://github.com/acuteenvy/tlrc"
documentation = "https://acuteenvy.github.io/tlrc"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.5", features = ["derive", "cargo"] }
dirs = "5.0.1"
is-terminal = "0.4.7"
serde = { version = "1.0.162", features = ["derive"] }
toml = "0.7.3"
ureq = "2.6.2"
yansi = "0.5.1"
zip = { version = "0.6.4", default-features = false, features = ["deflate"] }

[[bin]]
name = "tldr"
path = "src/main.rs"

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
